# Generated by Django 6.0 on 2025-12-11 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='shop.seed')),
            ],
        ),
    ]
