# Generated by Django 6.0 on 2025-12-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_seedvariety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='price',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='stock',
        ),
    ]
