# Generated by Django 6.0 on 2025-12-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_seed_price_remove_seed_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seed',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
