# Generated by Django 6.0.2 on 2026-02-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
